[package]
name = "hello-world-mixed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jolt = { path = "../jolt" }
jolt-sys = { path = "../jolt-sys" }
